import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class ShareVerseFonts {
  static final Map<
      String,
      TextStyle Function(
          {TextStyle? textStyle,
          Color? color,
          Color? backgroundColor,
          double? fontSize,
          FontWeight? fontWeight,
          FontStyle? fontStyle,
          double? letterSpacing,
          double? wordSpacing,
          TextBaseline? textBaseline,
          double? height,
          Locale? locale,
          Paint? foreground,
          Paint? background,
          List<Shadow>? shadows,
          List<FontFeature>? fontFeatures,
          TextDecoration? decoration,
          Color? decorationColor,
          TextDecorationStyle? decorationStyle,
          double? decorationThickness})> fonts = {
    'Inter': GoogleFonts.inter,
    'Roboto': GoogleFonts.roboto,
    'Lato': GoogleFonts.lato,
    'Merriweather': GoogleFonts.merriweather,
    'Playfair': GoogleFonts.playfairDisplay,
    'Chathura': _localFont('Chathura'),
    'Annamayya': _localFont('Annamayya'),
    'Dhurjati': _localFont('Dhurjati'),
    'Gidugu': _localFont('Gidugu'),
    'Gurajada': _localFont('Gurajada'),
    'Jims': _localFont('Jims'),
    'Kanakadurga': _localFont('Kanakadurga'),
    'LakkiReddy': _localFont('LakkiReddy'),
    'Mallanna': _localFont('Mallanna'),
    'Mandali': _localFont('Mandali'),
    'Nandakam': _localFont('Nandakam'),
    'NATS': _localFont('NATS'),
    'NTR': _localFont('NTR'),
    'Peddana': _localFont('Peddana'),
    'Potti Sreeramulu': _localFont('Potti Sreeramulu'),
    'Purushothamaa': _localFont('Purushothamaa'),
    'Ramabhadra': _localFont('Ramabhadra'),
    'Ramaneeyawin': _localFont('Ramaneeyawin'),
    'RaviPrakash': _localFont('RaviPrakash'),
    'Seelaveerraju': _localFont('Seelaveerraju'),
    'SPBalasubrahmanyam': _localFont('SPBalasubrahmanyam'),
    'Sree Krushnadevaraya': _localFont('Sree Krushnadevaraya'),
    'Suranna': _localFont('Suranna'),
    'Suravaram': _localFont('Suravaram'),
    'Syamala Ramana': _localFont('Syamala Ramana'),
  };

  static final Map<String, String> displayNames = {
    'Inter': 'Inter',
    'Roboto': 'Roboto',
    'Lato': 'Lato',
    'Merriweather': 'Merriweather',
    'Playfair': 'Playfair',
    'Annamayya': 'అన్నమయ్య',
    'Chathura': 'చతుర',
    'Dhurjati': 'ధూర్జటి',
    'Gidugu': 'గిడుగు',
    'Gurajada': 'గురజాడ',
    'Jims': 'జిమ్స్',
    'Kanakadurga': 'కనకదుర్గ',
    'LakkiReddy': 'లక్కిరెడ్డి',
    'Mallanna': 'మల్లన్న',
    'Mandali': 'మండలి',
    'Nandakam': 'నందకం',
    'NATS': 'నాట్స్',
    'NTR': 'ఎన్టీఆర్',
    'Peddana': 'పెద్దన',
    'Potti Sreeramulu': 'పొట్టి శ్రీరాములు',
    'Purushothamaa': 'పురుషోత్తమ',
    'Ramabhadra': 'రామభద్ర',
    'Ramaneeyawin': 'రమణీయం',
    'RaviPrakash': 'రవిప్రకాష్',
    'Seelaveerraju': 'శీలవీర్రాజు',
    'SPBalasubrahmanyam': 'ఎస్.పి.బాలసుబ్రహ్మణ్యం',
    'Sree Krushnadevaraya': 'శ్రీ కృష్ణదేవరాయ',
    'Suranna': 'సూరన',
    'Suravaram': 'సురవరం',
    'Syamala Ramana': 'శ్యామల రమణ',
  };

  static TextStyle Function({
    TextStyle? textStyle,
    Color? color,
    Color? backgroundColor,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    Locale? locale,
    Paint? foreground,
    Paint? background,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
  }) _localFont(String fontFamily) {
    return ({
      textStyle,
      color,
      backgroundColor,
      fontSize,
      fontWeight,
      fontStyle,
      letterSpacing,
      wordSpacing,
      textBaseline,
      height,
      locale,
      foreground,
      background,
      shadows,
      fontFeatures,
      decoration,
      decorationColor,
      decorationStyle,
      decorationThickness,
    }) {
      return TextStyle(
        fontFamily: fontFamily,
        color: color,
        backgroundColor: backgroundColor,
        fontSize: fontSize,
        fontWeight: fontWeight,
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        height: height,
        locale: locale,
        foreground: foreground,
        background: background,
        shadows: shadows,
        fontFeatures: fontFeatures,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        decorationThickness: decorationThickness,
      );
    };
  }
}
