class ReadingPlanConstants {
  static const Map<String, String> teluguBookNames = {
    "Genesis": "ఆదికాండము",
    "Exodus": "నిర్గమకాండము",
    "Leviticus": "లేవీయకాండము",
    "Numbers": "సంఖ్యాకాండము",
    "Deuteronomy": "ద్వితీయోపదేశకాండము",
    "Joshua": "యెహోషువ",
    "Judges": "న్యాయాధిపతులు",
    "Ruth": "రూతు",
    "1Samuel": "1 సమూయేలు",
    "2Samuel": "2 సమూయేలు",
    "1Kings": "1 రాజులు",
    "2Kings": "2 రాజులు",
    "1Chronicles": "1 దినవృత్తాంతములు",
    "2Chronicles": "2 దినవృత్తాంతములు",
    "Ezra": "ఎజ్రా",
    "Nehemiah": "నెహెమ్యా",
    "Esther": "ఎస్తేరు",
    "Job": "యోబు",
    "Psalm": "కీర్తనలు",
    "Proverbs": "సామెతలు",
    "Ecclesiastes": "ప్రసంగి",
    "SongOfSongs": "పరమగీతము",
    "Isaiah": "యెషయా",
    "Jeremiah": "యిర్మియా",
    "Lamentations": "విలాపవాక్యములు",
    "Ezekiel": "యెహెజ్కేలు",
    "Daniel": "దానియేలు",
    "Hosea": "హోషేయ",
    "Joel": "యోవేలు",
    "Amos": "ఆమోసు",
    "Obadiah": "ఓబద్యా",
    "Jonah": "యోనా",
    "Micah": "మీకా",
    "Nahum": "నహూము",
    "Habakkuk": "హబక్కూకు",
    "Zephaniah": "జెఫన్యా",
    "Haggai": "హగ్గయి",
    "Zechariah": "జెకర్యా",
    "Malachi": "మలాకీ",
    "Matthew": "మత్తయి సువార్త",
    "Mark": "మార్కు సువార్త",
    "Luke": "లూకా సువార్త",
    "John": "యోహాను సువార్త",
    "Acts": "అపోస్తలుల కార్యములు",
    "Romans": "రోమీయులకు",
    "1Corinthians": "1 కోరింథీయులకు",
    "2Corinthians": "2 కోరింథీయులకు",
    "Galatians": "గలతీయులకు",
    "Ephesians": "ఎఫెసీయులకు",
    "Philippians": "ఫిలిప్పీయులకు",
    "Colossians": "కొలొస్సయులకు",
    "1Thessalonians": "1 థెస్సలొనీకయులకు",
    "2Thessalonians": "2 థెస్సలొనీకయులకు",
    "1Timothy": "1 తిమోతికి",
    "2Timothy": "2 తిమోతికి",
    "Titus": "తీతుకు",
    "Philemon": "ఫిలేమోనుకు",
    "Hebrews": "హెబ్రీయులకు",
    "James": "యాకోబు",
    "1Peter": "1 పేతురు",
    "2Peter": "2 పేతురు",
    "1John": "1 యోహాను",
    "2John": "2 యోహాను",
    "3John": "3 యోహాను",
    "Jude": "యూదా",
    "Revelation": "ప్రకటన గ్రంథము",
    // M'Cheyne abbreviations or variations if any
    "1 Thes": "1 థెస్సలొనీకయులకు",
    "2 Thes": "2 థెస్సలొనీకయులకు",
  };

  static const Map<String, int> englishBookToId = {
    "Genesis": 1,
    "Exodus": 2,
    "Leviticus": 3,
    "Numbers": 4,
    "Deuteronomy": 5,
    "Joshua": 6,
    "Judges": 7,
    "Ruth": 8,
    "1Samuel": 9,
    "2Samuel": 10,
    "1Kings": 11,
    "2Kings": 12,
    "1Chronicles": 13,
    "2Chronicles": 14,
    "Ezra": 15,
    "Nehemiah": 16,
    "Esther": 17,
    "Job": 18,
    "Psalm": 19,
    "Proverbs": 20,
    "Ecclesiastes": 21,
    "SongOfSongs": 22,
    "Isaiah": 23,
    "Jeremiah": 24,
    "Lamentations": 25,
    "Ezekiel": 26,
    "Daniel": 27,
    "Hosea": 28,
    "Joel": 29,
    "Amos": 30,
    "Obadiah": 31,
    "Jonah": 32,
    "Micah": 33,
    "Nahum": 34,
    "Habakkuk": 35,
    "Zephaniah": 36,
    "Haggai": 37,
    "Zechariah": 38,
    "Malachi": 39,
    "Matthew": 40,
    "Mark": 41,
    "Luke": 42,
    "John": 43,
    "Acts": 44,
    "Romans": 45,
    "1Corinthians": 46,
    "2Corinthians": 47,
    "Galatians": 48,
    "Ephesians": 49,
    "Philippians": 50,
    "Colossians": 51,
    "1Thessalonians": 52,
    "2Thessalonians": 53,
    "1Timothy": 54,
    "2Timothy": 55,
    "Titus": 56,
    "Philemon": 57,
    "Hebrews": 58,
    "James": 59,
    "1Peter": 60,
    "2Peter": 61,
    "1John": 62,
    "2John": 63,
    "3John": 64,
    "Jude": 65,
    "Revelation": 66,
    // Variations found in plan
    "1 Thes": 52,
    "2 Thes": 53,
    "1 Corinthians": 46,
    "2 Corinthians": 47,
  };

  static String getTeluguBookName(String englishName) {
    // Handle variations like "1 Thes" vs "1Thessalonians"
    if (teluguBookNames.containsKey(englishName)) {
      return teluguBookNames[englishName]!;
    }
    // Fallback logic
    return englishName;
  }
}
